// <auto-generated />
namespace SkyFan.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class orderdetails3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(orderdetails3));
        
        string IMigrationMetadata.Id
        {
            get { return "201802051100481_orderdetails3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
